language: node_js
node_js:
  - 4
script:
- bash .build.sh
after_success:
- bash .deploy.sh
env:
  global:
    secure: "MAyzS0njLFJMGTexvxvvV2VHgfc/SzeONPKH6H8vj7a9IwKcODxBhl0vBC5Odmq0mQO43aIFXtAfM+NfqVcMff43/OBbrG0mezupG6GUVtgIHKGzlAv76wvNqPes+DYKfOeTFSo/H2CwZB4DJfHlVjEoONrNZcTUjAUABLqRJORdAgfFIk9J/91s+yMLYbRbo6pQO8RutNsws9oyM1QxTQvgTPkbfiUlQSmNPy6eNJZzDabfTl1kXNfNM75oVW1rhTvmPcq9H5f4jcQVG1gYU2Um9vVRr1Da11ZfnM4xLBzvhDodnUczEpEkBZ6ucU4ykUGDZM8f7hzKsw66rS+p00ywhCiblV16mWNkmirJcZknhIQFRPfoYrVTrUvLt+3xnpUjOn07UdG3uc4hNVkmHKzG7LDtY3YAa6cA8e5W0o/GNoUvLLnEXJ8CKM+qq4cecttSGpylznHjQUrgosbEazu7lHsVnB5vTt0x5nFsdKcPXLpzXclusk3mXcwaLWnlDgdZCjOBCjpvZLRAHjBXPHcKWe0mwmpECz6c5whpFqAms5a79W50UAVUOfdZqP8o3+4cN1jO8Ht/jEK9omC29gKA2MaZqVgnqssQkw3R+eq11UlVZnRoMlGaMHd0yI9z9SnMP3YTvvWVn/TO0IZbwkT1GpWsJlrd37Txg1Bzi9w="
notifications:
  slack:
    secure: llNnXYQ/1R8QTDvodbM5MfLJMIrOSvYMvJY7Btit0vbwXfEgCpcoPNgQZK0Ol1yergnWkwwWNhMvBi5TQEaCJq5R7jHjD0XDun7lgrVMsF3TdpZXq1Op7iHpO2MfojDbu6owNIbe1jsX0LZTud48KJkNXInnbVPzfOwlTUgweXuUAs3RFWb7+Z8KcPa5pBbVIUj363DWmCYzB0MfvcYq7u7ualCY/qgiKG1/KIeHUjOoRfJnpzZztHHkQPkpqvD00DnHgLkcAXg5SPRon9fiv6drDXFOtQ7juI2pSHiBpsmvFKAjq6w83MMnNUyAzRNRWPwTk9TKWJiM2iQ+I4DWm4FOq4GHOxoXami094aiuv4AznMumZRIuN33+Ac/OsFdo2v1t/Efjx1sZyTGp/uYvMKtRtLkiO06r1bhowSkpseAv2ivbAcJGqupYvCApJZPYsF8EM2Jx1MY2Nw2QpBK1Y1BYvbS0UiTAVa7e6ECHrys1+wj07l8zvazJoa2SF/vss7KbCJR6G8qVtIgW2HaeWZeS8leFfzXC/v658zrp9TQnj4BK5JFQISyLLBzmxWPsWpwtCoMJH6z4WxIioy9yiBD//6ZMqsSi9cFbtMtEFR8BesQlOm380I1pjn4SaNr4H6LyX3Lzog0lylXDkP5Q51KjivslS/fZbwsL7/p3dk=
